apiVersion: apps/v1
kind: Deployment
metadata:
  name: sid-deployment
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      apptype: frontend
      env: test
  template:
    metadata:
      labels:
        apptype: frontend
        env: test
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1